### ISSUE TITLE
Version Don't Match

### ISSUE THREAD

**Issue by aimixsaka** [sqls-server/sqls#104]
\# internal/race
compile: version "go1.18.3" does not match go tool version "go1.18.4"
\# internal/goarch
compile: version "go1.18.3" does not match go tool version "go1.18.4"
\# encoding
compile: version "go1.18.3" does not match go tool version "go1.18.4"
\# internal/unsafeheader
compile: version "go1.18.3" does not match go tool version "go1.18.4"
......

**Comment by mattn** [comment]
Please try this again in latest Go version
