### ISSUE TITLE
Install fails on M1 mac

### ISSUE THREAD

**Issue by ashish10alex** [sqls-server/sqls#111]
I am getting the below error despite having done `go install github.com/lighttiger2505/sqls@latest`
strangely enough the process worked in my intel mac but not on the M1 mac. Is there an additional step I might be missing ?

Additional context -> 
 my sqls file resides in `/Users/username/go/bin` which the the case for my intel mac as well.
However I had to run `export GOPROXY=direct` on M1 mac before running `go install github.com/lighttiger2505/sqls@latest`

<img width="1495" alt="CleanShot 2022-11-06 at 11 09 00@2x" src="https://user-images.githubusercontent.com/34306898/200167241-be40960e-30e2-427c-9ca5-269586535b63.png">

- OS Version: Mac OS Monterey 12.6.1, M1 pro

**Comment by ashish10alex** [comment]
Managed to solve the above by using 
```
export GO111MODULE=on
export GOPROXY=https://goproxy.cn/
```

**Comment by mattn** [comment]
This is already resolved?

**Comment by mattn** [comment]
Pleaes file new issue if you still have same issue.
