### ISSUE TITLE
Installation Fails in Windows without a GCC compiler

### ISSUE THREAD

**Issue by Akrista** [sqls-server/sqls#158]
**Describe the bug**
Hey, i'm trying to install sqls using go install, but it seems to fail with godror

**To Reproduce**
1. Run
```console
go install github.com/sqls-server/sqls@latest
```
2. See error
```console
# github.com/godror/godror
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:563:19: undefined: VersionInfo
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:564:19: undefined: VersionInfo
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:565:10: undefined: StartupMode
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:566:11: undefined: ShutdownMode
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:568:31: undefined: Event
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:568:42: undefined: SubscriptionOption
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:568:64: undefined: Subscription
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:569:31: undefined: ObjectType
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:570:59: undefined: Data
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:571:28: undefined: DirectLob
go\pkg\mod\github.com\godror\godror@v0.41.0\orahlp.go:571:28: too many errors
```

**Expected behavior**
Success on the installation of the LSP

**Versions (please complete the following information):**
 - OS Version: Windows 11 Pro x86_64
 - sqls Version 0.2.27

**Additional context**
Seems to be similar to #109, tho, that was on an unix OS.

So far i tried to clean the cache with:

```console
go clean -cache -modcache
```

but this did not change the behavior as expected.

I also tried changing enable "CGO_ENABLED"
```console
go env -w CGO_ENABLED=1
```

but it seems that i'd need a C compiler to correctly install the LSP as per the output:
```console
# runtime/cgo
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
```
after using [tdm-gcc](https://jmeubank.github.io/tdm-gcc/download/) seems to install fine but maybe there's another option, i dunno just asking sorry for bothering.

Besides that thx for creating this LSP i mainly needed for the support that has on mssql

**Comment by mattn** [comment]
Yes, sqls uses go-sqlite3 which uses cgo.
