### ISSUE TITLE
Update readme to suggest adding the golang PPA

### ISSUE THREAD

**Issue by leabravo** [sqls-server/sqls#26]
The 18.04 repo has an outdated version of go which doesn't support os.GetUserHomeDir. Could you please consider adding the golang PPA to the README?

Update readme to suggest adding the golang PPA

```
sudo add-apt-repository ppa:longsleep/golang-backports
sudo apt-get update
sudo apt-get install golang-go
```

Thanks!

**Comment by mattn** [comment]
Currently this sqls support latest Go version.
