### ISSUE TITLE
Added sqls to scoop

### ISSUE THREAD

**Issue by alextwothousand** [sqls-server/sqls#48]
**Is your feature request related to a problem? Please describe.**
I've added sqls to the windows package manager, Scoop. Just add my bucket.
https://github.com/alextwothousand/scoop-bucket

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mattn** [comment]
Please do. This repository publish binary files.
