### ISSUE TITLE
Add Clickhouse support

### ISSUE THREAD

**Issue by r-zenine** [sqls-server/sqls#53]
Hello, 

First of all , thanks for the project, it looks great ! 

I would like to know if you would welcome clickhouse support in `sqls`. 
I could look at the code and see how I could make that happen. In addition, given that clickhouse is open source, we could integrate CI tests in your current workflow. 

Would you welcome such PR ? If so, could you point me to the right direction ? 

I was planing to use the [official go driver for clickhouse](https://github.com/ClickHouse/clickhouse-go)

Thanks 
Again, great work already ! 
Thank you for taking the time to build this LSP server.

**Comment by PhilipMok-cc** [comment]
I added oracle support PR, recently. I think it is the minimal change of adding a new driver. Please talk a look

**Comment by r-zenine** [comment]
Hello @PhilipMok-cc , 
Are you referring to this PR https://github.com/lighttiger2505/sqls/pull/78 ? 
I'll take a look next week-end to add the support of click house.

**Comment by PhilipMok-cc** [comment]
Yes, but there are some issue.
1. Testing required a service container to support.
Other than that the test routine is covered all the issue I have met during testing and I think it is generic to all kind of DB.

**Comment by franchb** [comment]
Hello!

Just mind that v2 version is on the road https://github.com/ClickHouse/clickhouse-go/releases/tag/v2.0.0-beta.5

Maintainers have already switched their production servers to v2.

**Comment by patrickpichler** [comment]
Hey :) 

I've created a PR to add clickhouse database support. I hope this is still wanted! 

(see #133)
