### ISSUE TITLE
Add json1 support for sqlite driver

### ISSUE THREAD

**Issue by FsharperOnTheRun** [sqls-server/sqls#62]
It seems there's no support for the json1 extension of sqlite.

```sql
select json_array(1, 2);
```
> no such function: json_array

And when I checked it seems the sqlite3 was not compiled with json1 extension.

```sql
PRAGMA compile_options;
```

> +----------------------------+
> |      COMPILE OPTIONS       |
> +----------------------------+
> | COMPILER=gcc-11.1.0        |
> | DEFAULT_WAL_SYNCHRONOUS=1  |
> | ENABLE_FTS3                |
> | ENABLE_FTS3_PARENTHESIS    |
> | ENABLE_RTREE               |
> | ENABLE_UPDATE_DELETE_LIMIT |
> | OMIT_DEPRECATED            |
> | SYSTEM_MALLOC              |
> | THREADSAFE=1               |
> +----------------------------+

I'm on: Emacs 28.0.50 on Manjaro Linux

So far I'm using sqlite inferior process to send queries instead of lsp.

If there's documentation on how to manually update the drivers, sorry. I think it only needs to be built with json1 tag.

**Comment by mattn** [comment]
This is already done. go-sqlite3 support json1 builtin.
