### ISSUE TITLE
Oracle support

### ISSUE THREAD

**Issue by PhilipMok-cc** [sqls-server/sqls#76]
I am trying to enable oracle support by adding a file oracle.go to 
/internal/database/

I use docker with oracle xe to boot of a instance of oracle to test.

but I have some question:
1. [Solved]I download the project but could not compile, I could unit test with oracle_test.go
2. The test case seem not complete. [in progress]
3. Seem keyword.go need to be update. Any other file is related to db connection? [Working on the branch]
4. does the password is required to coded in the config? [Hard code as a temp solution]

Are there any related document about this?

**Comment by levouh** [comment]
@PhilipMok-cc did you make any progress on this? Wanted to take a stab at this myself as well and curious how far you got.

**Comment by levouh** [comment]
Actually looks like something was merged via `6329f68115410446daa84ff73e11e6995ce5342b`, awesome!

**Comment by mattn** [comment]
If you still have this issue, please file new issue. I guess this is already resolved.
